import { execFileSync } from "node:child_process";
const validationEntries = ["urp-taa-start","urp-fullchain-aligned","urp-mpb-timing-a","urp-mpb-timing-b","urp-panty-aligned","urp-old-baseline-shadow-inputs","urp-old-baseline-perf","urp-old-baseline-noaa","urp-old-baseline-open","urp-old-baseline-capture","urp-old-baseline-exit","urp-animation-prepare","urp-animation-run","urp-animation-restore","urp-baseline-hop-return","urp-baseline-hop-check","urp-baseline-hop-exit","urp-panty-ingestion", "urp-prefab-boundary", "urp-recover-scene", "urp-integer-transport", "urp-pantyhose", "urp-world-shadow", "urp-scene-shadow-reload", "urp-scene-lifecycle", "urp-tone-witness", "urp-scene-shadow-import", "urp-irradiance-import", "urp-shadow-flags", "urp-bound-response", "urp-cloth-inputs", "urp-scene", "urp-game", "urp-baseline-scene", "urp-setup-fault", "urp-post-fault", "urp-tone", "urp-overlay-reload", "urp-material-workflow", "urp-edit-mode", "camera", "history-clear", "preview", "preview-restart", "diagnostic-preview", "dynamic", "reference", "configure", "lifecycle", "regression", "repair-check", "repair-restore", "rendering-defaults", "rendering-defaults-check", "asset-migration-audit", "formal-scenes-smoke", "shader-family-prepare", "shader-family-parity", "display-presentation", "eye-matrix-check", "scene-target-prototype", "material-authoring-configure", "material-authoring-default", "material-authoring-edit", "material-authoring-session", "scene-preview-check", "material-response-check", "scene-multiview-check", "material-pantyhose-check", "scene-multiview-safety", "scene-window-control", "scene-window-enabled-control", "scene-window-active-close", "scene-safety4", "scene-safety8", "scene-selection-check", "hair-coverage-prepare", "hair-coverage-check", "scene-lifecycle-check", "scene-parameters-capture", "scene-preview-enable", "skin-gpu-body", "skin-gpu-all", "skin-gpu-blend", "scene-continuous-check", "scene-dirty-capture", "scene-dirty-verify", "scene-dirty-restore", "scene-continuous-short"];
export const editorTools = [
  { name:"launch_endfield_baseline_hop", description:"Launch only the fixed isolated Built-in baseline or current Endfield project, after all Unity Editors have exited. Dedicated local MCP port, no automatic capture.", inputSchema:{type:"object",properties:{project:{type:"string",enum:["baseline","current"]},attempt:{type:"integer",minimum:1,maximum:5},replaceFailedPid:{type:"integer",minimum:1}},required:["project","attempt"],additionalProperties:false}},
  { name: "launch_endfield_editor", description: "Launch only the fixed Endfield Unity 2021 Editor project after ensuring no Unity Editor remains, with a fresh recovery log and hidden startup; does not resume validation or save scenes.", inputSchema: { type: "object", properties: { attempt: { type: "integer", minimum: 1, maximum: 5 }, replaceFailedPid: { type: "integer", minimum: 1 }, fixedUpm: { type: "boolean" } }, required: ["attempt"], additionalProperties: false } },
  { name: "cancel_urp_validation", description: "Cancel the active bounded URP response or Scene-lifecycle test by its exact job ID, restoring its owned temporary state and recording failure; only installed safe suites are accepted.", inputSchema: { type: "object", properties: { jobId: { type: "string" } }, required: ["jobId"], additionalProperties: false } },
  { name: "get_editor_state", description: "Read Editor play/compile state and recent compile diagnostics.", inputSchema: { type: "object", properties: {}, additionalProperties: false } },
  { name: "refresh_editor", description: "Request AssetDatabase refresh in the current Editor; poll get_editor_state for compile completion.", inputSchema: { type: "object", properties: {}, additionalProperties: false } },
  { name: "set_editor_play_mode", description: "Enter, exit, pause, or resume the currently loaded scene. Does not save or replace scenes.", inputSchema: { type: "object", properties: { action: { type: "string", enum: ["enter", "exit", "pause", "resume"] } }, required: ["action"], additionalProperties: false } },
  { name: "run_lobby_aa_validation", description: "Run one explicitly installed rendering or asset-migration validation entry; no arbitrary C# or menu execution.", inputSchema: { type: "object", properties: { entry: { type: "string", enum: validationEntries }, output: { type: "string" }, statePath: { type: "string" } }, required: ["entry", "output"], additionalProperties: false } },
  { name: "set_asset_migration_state", description: "Own/release the current Editor auto-refresh and assembly-reload freeze for asset migration; Edit mode only.", inputSchema: { type: "object", properties: { action: { type: "string", enum: ["lock", "unlock"] } }, required: ["action"], additionalProperties: false } }
];
export async function callEditorTool(name, client, args = {}) {
  switch (name) {
    case "launch_endfield_baseline_hop": {
      if(!["baseline","current"].includes(args.project)||!Number.isInteger(args.attempt)||args.attempt<1||args.attempt>5)throw new Error("Fixed project and bounded attempt required");
      const project="D:/Endfield/Research/validation/"+(args.project==="baseline"?"Unity2021-Baseline-20260914_01":"Unity2021");
      const port=args.project==="baseline"?51235:51234;
      const folder="D:/Endfield/Delivery/evidence/Audits/URPMigration20260914_01/BaselineHopLaunch-"+args.project+"-"+args.attempt;
      let stop="";
      if(args.replaceFailedPid!==undefined){if(args.project!=="baseline"||args.attempt<2||!Number.isInteger(args.replaceFailedPid)||args.replaceFailedPid<1)throw new Error("Only preceding owned baseline bootstrap may be replaced");const previous=folder.slice(0,-1)+(args.attempt-1);stop="$owned=Get-CimInstance Win32_Process -Filter 'ProcessId="+args.replaceFailedPid+"'; if(!$owned -or $owned.Name -ne 'Unity.exe' -or !$owned.CommandLine.Contains('"+project+"') -or !$owned.CommandLine.Contains('"+previous+"/Editor.log')){throw 'Wrong owned bootstrap PID'}; $oldLog=Get-Content -LiteralPath '"+previous+"/Editor.log' -Raw;if(!$oldLog.Contains('error CS') -or $oldLog.Contains('[UnityMcp] Listening')){throw 'Not untouched failed initial compilation'}; Stop-Process -Id "+args.replaceFailedPid+"; Start-Sleep -Milliseconds 500; ";}
      const script="$ErrorActionPreference='Stop'; "+stop+"if(Get-Process -Name Unity -ErrorAction SilentlyContinue){throw 'Unity Editor still exists; serial handoff required'}; if(Test-Path -LiteralPath '"+folder+"'){throw 'Fresh attempt required'}; if(!(Test-Path -LiteralPath '"+project+"/ProjectSettings/ProjectVersion.txt')){throw 'Fixed project missing'}; New-Item -ItemType Directory -Path '"+folder+"'|Out-Null; $env:UNITY_MCP_PORT='"+port+"'; $p=Start-Process -FilePath 'C:/Program Files/Unity/Hub/Editor/2021.3.34f1/Editor/Unity.exe' -ArgumentList @('-projectPath','"+project+"','-logFile','"+folder+"/Editor.log') -WorkingDirectory '"+project+"' -WindowStyle Hidden -PassThru; @{pid=$p.Id;project='"+project+"';port="+port+";log='"+folder+"/Editor.log';automaticValidation=$false}|ConvertTo-Json -Compress";
      return {ok:true,data:JSON.parse(execFileSync("powershell.exe",["-NoProfile","-NonInteractive","-Command",script],{encoding:"utf8",windowsHide:true}))};
    }
    case "launch_endfield_editor": {
      if(!Number.isInteger(args.attempt)||args.attempt<1||args.attempt>5)throw new Error("Bounded attempt 1..5 required");
      const folder="D:/Endfield/Delivery/evidence/Audits/URPMigration20260914_01/EditorExit20260914_0450/Relaunch"+String(args.attempt).padStart(2,"0");
      let stop="";
      if(args.replaceFailedPid!==undefined){
        if(!Number.isInteger(args.replaceFailedPid)||args.replaceFailedPid<1||args.attempt<2)throw new Error("Exact owned failed-bootstrap PID required");
        const oldFolder=folder.slice(0,-2)+String(args.attempt-1).padStart(2,"0");
        stop="$p=Get-CimInstance Win32_Process -Filter 'ProcessId="+args.replaceFailedPid+"'; if(!$p -or $p.Name -ne 'Unity.exe' -or !$p.CommandLine.Contains('"+oldFolder+"/Editor.log')){throw 'PID does not match preceding owned recovery launch'}; $log=Get-Content -LiteralPath '"+oldFolder+"/Editor.log' -Raw; if(!$log.Contains('Failed to start the Unity Package Manager') -or $log.Contains('[UnityMCP]')){throw 'Not the known pre-project UPM bootstrap failure'}; Stop-Process -Id "+args.replaceFailedPid+"; Start-Sleep -Milliseconds 500; Get-CimInstance Win32_Process -Filter \"name='UnityPackageManager.exe'\" | Where-Object {$_.CommandLine -match '-s "+args.replaceFailedPid+"(?: |$)'} | ForEach-Object {Stop-Process -Id $_.ProcessId}; ";
      }
      const upm=args.fixedUpm?"$listener=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,19577); $listener.Start(); $listener.Stop(); $upmProcess=Start-Process -FilePath 'C:/Program Files/Unity/Hub/Editor/2021.3.34f1/Editor/Data/Resources/PackageManager/Server/UnityPackageManager.exe' -ArgumentList @('-p','19577','-cl','5','-l','5') -WorkingDirectory 'C:/Program Files/Unity/Hub/Editor/2021.3.34f1/Editor/Data/Resources/PackageManager/Server' -WindowStyle Hidden -RedirectStandardOutput '"+folder+"/upm-stdout.log' -RedirectStandardError '"+folder+"/upm-stderr.log' -PassThru; $upmPid=$upmProcess.Id; $ready=$false; for($i=0;$i -lt 20;$i++){try{$h=Invoke-RestMethod -Uri 'http://127.0.0.1:19577/health' -TimeoutSec 1;if($h.status -eq 'OK'){$ready=$true;break}}catch{};Start-Sleep -Milliseconds 100}; if(!$ready){throw 'Owned UPM did not become ready; inspect task stdout/stderr'}; ":"$upmPid=0; ";
      const script="$ErrorActionPreference='Stop'; "+stop+"if(Get-Process -Name Unity -ErrorAction SilentlyContinue){throw 'Unity Editor already exists'}; if(Test-Path -LiteralPath '"+folder+"'){throw 'Fresh recovery attempt required'}; New-Item -ItemType Directory -Path '"+folder+"' | Out-Null; "+upm+"$editorProcess=Start-Process -FilePath 'C:/Program Files/Unity/Hub/Editor/2021.3.34f1/Editor/Unity.exe' -ArgumentList @('-projectPath','D:/Endfield/Research/validation/Unity2021','-logFile','"+folder+"/Editor.log'"+(args.fixedUpm?",'-upmServerPort','19577'":"")+") -WorkingDirectory 'D:/Endfield/Research/validation/Unity2021' -WindowStyle Hidden -PassThru; @{launched=$true;pid=$editorProcess.Id;upmPid=$upmPid;project='D:/Endfield/Research/validation/Unity2021';log='"+folder+"/Editor.log';automaticValidation=$false} | ConvertTo-Json -Compress";
      const result=JSON.parse(execFileSync("powershell.exe",["-NoProfile","-NonInteractive","-Command",script],{encoding:"utf8",windowsHide:true}));return {ok:true,data:result};
    }
    case "cancel_urp_validation": if(typeof args.jobId!=="string"||!args.jobId)throw new Error("Exact job ID required");return client.post("/api/editor/validation-cancel",{jobId:args.jobId});
    case "get_editor_state": return client.get("/api/editor/state");
    case "refresh_editor": return client.post("/api/editor/refresh");
    case "set_editor_play_mode":
      if (!["enter", "exit", "pause", "resume"].includes(args.action)) throw new Error("Invalid play action");
      return client.post("/api/editor/play-mode", { action: args.action });
    case "run_lobby_aa_validation":
      if (!validationEntries.includes(args.entry) || typeof args.output !== "string") throw new Error("Invalid validation entry/output");
      return client.post("/api/editor/validation", { entry: args.entry, output: args.output, statePath: args.statePath });
    case "set_asset_migration_state":
      if (!["lock", "unlock"].includes(args.action)) throw new Error("Invalid migration action");
      return client.post("/api/editor/asset-migration", { action: args.action });
    default: return null;
  }
}
